### ISSUE TITLE
Docs website hamburger menu cut off on mobile

### ISSUE THREAD

**Issue by AdamBrousseau** [eclipse/openj9-docs#425]
**Subject:**
Extracted from https://github.com/eclipse/openj9-docs/issues/420#issuecomment-550448025
Top left "hamburger" menu is slightly cutoff on mobile.
![Screenshot_20191106-115912__01](https://user-images.githubusercontent.com/6430052/68329082-838b5200-009e-11ea-9657-04f5f3c3d1b6.jpg)

**Suggestion:**

**Comment by Bazif-Khan** [comment]
I can't reproduce it, and I think this issue is fixed. Please see the screenshot.

Could you please let me know how I can reproduce it? Thanks

![image](https://user-images.githubusercontent.com/51790085/68582014-aa1c0500-0471-11ea-818c-3da213401289.png)

**Comment by SueChaplain** [comment]
@AdamBrousseau - are you still seeing this problem please? If so, can you tell me what your mobile device is. We can't seem to re-create this. Thank you

**Comment by AdamBrousseau** [comment]
Confirm it renders properly on Android Chrome/Firefox/DuckDuckGo. Thanks!

**Comment by pmhayward** [comment]
Not sure if worth reopening for this, but I still see the problem to some extent (Honor 10 Lite, Android, Chrome). 
All is fine in portrait mode (header bar and menu are removed completely when scrolling up, and reappear when scrolling down). 
But in landscape mode, header bar and menu are only half removed when scrolling up, though pull back OK when scrolling down. (But menu pretty unusable in portrait mode anyway - menu header takes up most of available vertical space!)
